brew "clang-format"
brew "cmake"
brew "exiftool"
brew "git-lfs"
brew "mas"
brew "openssl@3"
brew "pandoc"
brew "starship"
brew "zsh"
cask "clip-studio-paint"
cask "colorchecker-camera-calibration"
cask "discord"
cask "firefox"
cask "font-im-fell-dw-pica"
cask "font-im-fell-great-primer-sc"
cask "font-monaspace"
cask "ghostty"
cask "google-chrome"
cask "jetbrains-toolbox"
cask "logitech-g-hub"
cask "mactex-no-gui"
cask "obsidian"
cask "steam"
cask "unity"
cask "unity-hub"
cask "utm"
cask "visual-studio-code"
cask "wacom-tablet"
cask "zoom"
mas "Blackmagic Disk Speed Test", id: 425264550
mas "Copilot", id: 6738511300
mas "Keynote", id: 409183694
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 361304891
mas "Pages", id: 361309726
mas "Pixen", id: 525180431
mas "Xcode", id: 497799835
vscode "arm.armls"
vscode "charliermarsh.ruff"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.hexeditor"
vscode "ms-vsliveshare.vsliveshare"
vscode "teabyii.ayu"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
uv "ruff"
